### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by lee-dohm** [facto/espec_phoenix_helpers#1]
I've been using these helpers in one of my own projects that I'm converting to ESpec and found them very useful, thank you :bow: I would like to contribute back to the project but I noticed there is no `LICENSE` file or mention of a license in the `README`. Since [no license](https://choosealicense.com/no-license/) does not grant me the right to modify the source code, I am hoping that you can clarify the situation by adding one.

Thank you in advance and please let me know if you have any questions!

**Comment by joshrieken** [comment]
Hiya! 

I added a license (Apache 2.0, same as espec).

Hope that helps.

**Comment by lee-dohm** [comment]
It does indeed, thank you! :bow:
